version: "3"
services:

  teamcity:
    image: jetbrains/teamcity-server
    container_name: jetbrains_teamcity
    restart: always
    volumes:
      - ./data:/data/teamcity_server/datadir
      - ./logs:/opt/teamcity/logs
    ports:
      - 8111:8111